import { PDFReportData } from "../types/report.types";

// stream PDFs directly instead of saving to disk
export const streamPDF = (doc: any, data: PDFReportData) => {
  doc.fontSize(22).text("LoanLink", { align: "center" });

  doc.moveDown();

  doc.fontSize(16).text("AI Loan Summary Report", {
    align: "center",
  });

  doc.moveDown();

  doc.fontSize(14).text(`Applicant: ${data.applicantName}`);
  doc.text(`Loan Amount: ${data.loanAmount}`);
  doc.text(`Duration: ${data.duration} months`);
  doc.text(`Purpose: ${data.purpose}`);

  doc.moveDown();

  doc.fontSize(16).text("Executive Summary");
  doc.fontSize(12).text(data.summary);

  doc.moveDown();

  doc.fontSize(16).text("Repayment Analysis");
  doc.fontSize(12).text(data.repaymentAnalysis);

  doc.moveDown();

  doc.fontSize(16).text("Risk Analysis");
  doc.fontSize(12).text(data.riskAnalysis);

  doc.moveDown();

  doc.fontSize(16).text("Recommendations");

  data.recommendations.forEach((item, index) => {
    doc.text(`${index + 1}. ${item}`);
  });

  doc.moveDown(2);

  doc.fontSize(10).text("Generated by LoanLink AI", {
    align: "center",
  });
};
